version: '3'
services:
  app:
    build:
      context: ./docker
    volumes:
      - ./:/var/www/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
  nginx:
    image: nginx
    depends_on: [app]
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/app
    ports:
      - "${DOCKER_WEB_PORT}:80"
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: bd_blog
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "${DOCKER_DB_PORT}:3306"
    volumes:
      - ./:/var/www/app

